// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPs2aF7sa9eV3NS-XiMILAuWjQ_I7ASQo',
    appId: '1:547739251647:web:925170148d753189bae70a',
    messagingSenderId: '547739251647',
    projectId: 'kidschaupaltrustedcarpool',
    authDomain: 'kidschaupaltrustedcarpool.firebaseapp.com',
    storageBucket: 'kidschaupaltrustedcarpool.firebasestorage.app',
    measurementId: 'G-4WXFPTER66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN22fdQCVM0PnNv8nAFrGqFnk54W2eQsE',
    appId: '1:547739251647:android:1a93bb70ded708a0bae70a',
    messagingSenderId: '547739251647',
    projectId: 'kidschaupaltrustedcarpool',
    storageBucket: 'kidschaupaltrustedcarpool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkO55e6WxolCl1DNnGOpsPmZCCSpjCqgA',
    appId: '1:547739251647:ios:69e31b2777337785bae70a',
    messagingSenderId: '547739251647',
    projectId: 'kidschaupaltrustedcarpool',
    storageBucket: 'kidschaupaltrustedcarpool.firebasestorage.app',
    iosBundleId: 'com.example.kidschaupaltrustedcarpool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkO55e6WxolCl1DNnGOpsPmZCCSpjCqgA',
    appId: '1:547739251647:ios:69e31b2777337785bae70a',
    messagingSenderId: '547739251647',
    projectId: 'kidschaupaltrustedcarpool',
    storageBucket: 'kidschaupaltrustedcarpool.firebasestorage.app',
    iosBundleId: 'com.example.kidschaupaltrustedcarpool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPs2aF7sa9eV3NS-XiMILAuWjQ_I7ASQo',
    appId: '1:547739251647:web:87f39dc3682ffb76bae70a',
    messagingSenderId: '547739251647',
    projectId: 'kidschaupaltrustedcarpool',
    authDomain: 'kidschaupaltrustedcarpool.firebaseapp.com',
    storageBucket: 'kidschaupaltrustedcarpool.firebasestorage.app',
    measurementId: 'G-X54Y409J4S',
  );
}
